### ISSUE TITLE
non-ASCII character issue

### ISSUE THREAD

**Issue by Sinan81** [python-pillow/pillow-perf#101]
When I attempt to run it, I am getting the following error:
```
$ ./run.py test_suite pillow_allocate
  File "./run.py", line 29
SyntaxError: Non-ASCII character '\xc3' in file ./run.py on line 29, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
where lin29 is:
```
26 
 27 
 28 def pixel_size(arg):
 29     for sep in [',', '*', 'x', '×']:
 30         if sep in arg:
 31             arg = arg.split(sep)
```

My setup is: Python 2.7.5, pillow-perf master branch, Centos7

**Comment by Sinan81** [comment]
Turns out one needs to put an encoding hint at the top of the file:
```
#!/usr/bin/python
# coding=utf-8
...
```

**Comment by Sinan81** [comment]
same error for other scripts ...

**Comment by Sinan81** [comment]
Next error:
```
$ ./run.py allocate
('\nAllocate', '2560\xc3\x971600', 'RGB', 'image')
    mode L              0.00013 s 30569.16 Mpx/s
    mode LA             0.00064 s  6429.59 Mpx/s
    mode RGB            0.00060 s  6817.41 Mpx/s
    mode RGBA           0.00061 s  6758.41 Mpx/s
Traceback (most recent call last):
  File "./run.py", line 69, in <module>
    test = case(args.size, args.mode)
  File "/mnt/local/pillow-perf/testsuite/cases/base.py", line 18, in newfunc
    return func(*(fargs + args), **newkeywords)
  File "/mnt/local/pillow-perf/testsuite/cases/base.py", line 31, in __init__
    self.data = self.create_test_data()
  File "/mnt/local/pillow-perf/testsuite/cases/pillow_allocate.py", line 13, in create_test_data
    im = super().create_test_data()[0]
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by hugovk** [comment]
Please use Python 3.

Python 2.7 has been EOL for 6 months and is no longer supported (see https://github.com/python-pillow/pillow-perf/pull/92).

**Comment by Sinan81** [comment]
Many HPC centers and enterprises run Centos7, for which default python is 2. EOL for Centos 7 is 2024. Of course I prefer using Python3, but the test I was doing (see below) required working with default python.

Test: compare binary installation of Pillow using its own pre-compiled libs vs non-binary installation using libs provided by Centos7.

**Comment by homm** [comment]
You still could sheckout previous commit where python 2 support were not removed.

**Comment by Sinan81** [comment]
Makes sense! Thanks
